apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "push-pr"
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[push]"
spec:
  pipelineSpec:
    tasks:
      - name: stepactions-task
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "hello this is the secret {{ git-auth-secret }}"
                exit 0

